In [1]:
import numpy as np

In [30]:
r1 = int(input("No. of Rows for m1: "))
c1=int(input("No. of Cols for m2: "))
ele=list(map(int,input().split()))

m1 = np.array(ele).reshape(r1,c1)

r2 = int(input("No. of Rows for m2: "))
c2=int(input("No. of Cols for m2: "))
ele=list(map(int,input().split()))

m2 = np.array(ele).reshape(r2,c2)
print(m1)
print(m2)

No. of Rows for m1: 2
No. of Cols for m2: 3
1 2 3 4 5 6
No. of Rows for m2: 2
No. of Cols for m2: 3
7 8 9 0 1 2
[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [0 1 2]]


In [45]:
33 # basic calc

opt;
while (opt<=9):

  opt=int(input("Enter Option: "))
  try:
    np.broadcast_shapes(m1.shape,m2.shape)

    if(opt ==1):
      print("add: ",m1+m2)
      continue
    elif(opt==2):
      print("subtract: ",m1-m2)
      continue
    elif(opt==3):
      print("multiply: ",m1*m2)
      continue
    elif(opt==4):
      print("divide: ",m1/m2)
      continue
    elif(opt==5):
      print(np.stack((m1,m2),axis=-1))
    else:
      print("exiting")
      break;
  except ValueError:
    print("Invalid")


Enter Option: 5
[[[1 7]
  [2 8]
  [3 9]]

 [[4 0]
  [5 1]
  [6 2]]]
Enter Option: 7
exiting
