In [17]:
import numpy as np
# defining
numpy_array = np.array([[1,2,3,4],[4,5,6,7.2],[1,2,3,4],[4,5,6,7]])
numpy_array

array([[1. , 2. , 3. , 4. ],
       [4. , 5. , 6. , 7.2],
       [1. , 2. , 3. , 4. ],
       [4. , 5. , 6. , 7. ]])

In [18]:
#datatype
numpy_array.dtype

dtype('float64')

In [19]:
# dimensions of the 2d array
numpy_array.shape

(4, 4)

In [20]:
#size
numpy_array.size

16

In [21]:
#dimension of the array
numpy_array.ndim

2

In [31]:
#initializing an array with 0 value
zeroes = np .zeros(3)
print(zeroes)

arr=np.zeros((2,4),dtype=int)
print(arr)

[0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]]


In [34]:
#intializing array with 1's

ar1=np.ones((3,3), dtype=int)
print(ar1)



[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [50]:
#array range np.arrange(start,stop,step,dtype)

arr1=np.arange(1,15,2,dtype=float)
arr1
arr2=arr.astype(float)
arr2


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
# printoptions - to format the float type printed aka. get the 0's to appear in the float digitsi in martix
#np.set_printoptions(precision=4,floatmode='fixed')
#np.arange(10,dtype=float)


array([0.0000, 1.0000, 2.0000, ..., 7.0000, 8.0000, 9.0000])

In [65]:
arr_reshape=np.array([1,2,3,4,5,6,7,8,9,10])
arr_reshape

array([ 1,  2,  3, ...,  8,  9, 10])

In [59]:
#RESHAPING THE ARRAY
  reshaped=arr_reshape.reshape(5,2)
  reshaped

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [66]:
#flatten matrix( reshape to 1d)
# flatten - creates a copy of the actual array and updates that , hence changes are temporary . Occupies more memory(creating a copy of array) and slower compared to ravel

flattened = reshaped.flatten()
flattened

array([ 1,  2,  3, ...,  8,  9, 10])

In [68]:
#ravel - flatten matrix
# ravel - manipulates the original array, hence changes are saved and reflected all thru. More memory efficient and faster since no copy is made of the array
raveled = reshaped.ravel()
raveled


array([ 1,  2,  3, ...,  8,  9, 10])

In [86]:
 #slicing

 arr=np.array([[1,2,3,4,5,6],[4,5,6,7,8,9],[4,2,5,2,5,1],[8,4,1,0,5,3]])
 arr
 #arr[0:2]
 #arr[1:1]
 # row, columns
 #arr[0:1 ,1:5]

array([[1, 2, 3, 4, 5, 6],
       [4, 5, 6, 7, 8, 9],
       [4, 2, 5, 2, 5, 1],
       [8, 4, 1, 0, 5, 3]])

In [89]:
#rows and columns
arr[0:3,1:5]

array([[2, 3, 4, 5],
       [5, 6, 7, 8],
       [2, 5, 2, 5]])

In [90]:
#skipping a number in between
arr[0:3:2,1:5:2]

array([[2, 4],
       [2, 2]])

In [92]:
#indexing

arr_ind=np.array([[1,2,3],[4,5,6]])
arr_ind

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
 arr[0][1]
 arr[3,5]

np.int64(3)

In [97]:
#indexing from end
arr5=np.array([1,2,3])
arr5[-1]

np.int64(3)

In [2]:
#random number generator
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [18]:
#generating random num using pcg64 with seed value . seed value = A seed value in a random number generator (RNG), specifically a pseudo-random number generator (PRNG), is an initial numerical value used to start the generation of a sequence of numbers. These numbers are not truly random but are calculated deterministically based on the seed and the PRNG's algorithm.used to maintain consistency in random num generation
arr7=gen(pcg(seed=44))
 #getting and printing the values in normal distribution with matrix size defined
arr7.normal(size=(5,5))

array([[ 1.44596273,  0.10230514,  0.32675278,  1.13646239,  0.82424394],
       [ 0.57895651, -0.37917058, -1.01887355,  0.3761689 , -0.51195951],
       [ 0.82723487,  0.21125445, -0.74529435,  0.26772526,  0.70918047],
       [ 0.17752012, -0.7825691 ,  0.262329  ,  0.3570017 ,  0.82428738],
       [ 0.72203442, -0.90825751, -0.49777136,  0.60571313, -1.6976786 ]])

In [19]:
arr7.integers(low=40,high=100,size=(9,9))

array([[53, 58, 90, 98, 98, 56, 82, 81, 59],
       [86, 79, 57, 60, 48, 63, 86, 75, 67],
       [90, 57, 51, 52, 66, 99, 73, 78, 90],
       [71, 74, 46, 57, 94, 84, 59, 75, 87],
       [43, 94, 56, 52, 94, 98, 50, 93, 72],
       [73, 68, 83, 75, 56, 47, 83, 61, 65],
       [98, 59, 45, 81, 88, 62, 92, 82, 53],
       [91, 70, 56, 80, 52, 60, 59, 53, 65],
       [99, 83, 79, 66, 78, 81, 50, 99, 49]])

In [29]:
#broadcasting : Broadcasting in NumPy is a mechanism that allows arithmetic operations to be performed on arrays of different shapes and sizes without explicitly creating copies of the smaller array to match the larger one. This feature significantly enhances efficiency and simplifies code when dealing with vectorized operations.

#  Broadcasting applies specific rules to find whether two arrays can be aligned for operations or not that are:

# 1. Check Dimensions: Ensure the arrays have the same number of dimensions or expandable dimensions.
# 2. Dimension Padding: If arrays have different numbers of dimensions the smaller array is left-padded with ones.
#3. Shape Compatibility: Two dimensions are compatible if they are equal or one of them is 1.
import numpy as np



In [30]:
#check dimensions and dimension padding
arr10=np.array([1,2,3])
arr11=np.array([[4],[5],[6]])
arr10*arr11

array([[ 4,  8, 12],
       [ 5, 10, 15],
       [ 6, 12, 18]])

In [31]:
#shape compatibility


# invalid case - a=2,3 and b= 2,4 - either both dimensions are same or 1 dimension is 1 in both
arr12=np.ones((1,4))
arr13=np.ones((3,1))
arr12*arr13

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
arr14=np.array([4,5,6])
arr15=np.array([[1],[2],[3]])

arr14+arr15

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [34]:
#array operations

arr111=np.array([1,4,7])
arr222=np.array([4,6,8])

In [35]:
arr111+arr222

array([ 5, 10, 15])

In [36]:
arr111*arr222

array([ 4, 24, 56])

In [37]:
arr111-arr222

array([-3, -2, -1])

In [38]:
arr111/arr222

array([0.25      , 0.66666667, 0.875     ])

In [40]:
print(np.dot(arr111,arr222))

84


In [51]:
# stack()  : stack() is used for joining multiple NumPy arrays. Unlike, concatenate(), it joins arrays along a new axis. It returns a NumPy array.
# to join 2 arrays, they must have the same shape and dimensions. (e.g. both (2,3)--> 2 rows,3 columns)
# stack() creates a new array which has 1 more dimension than the input arrays. If we stack 2 1-D arrays, the resultant array will have 2 dimensions.


#axis =0 -> row wise stacking
#axis=1 -> column wise stacking
m1 = np.array([[1,2,3],[3,4,6]])
m2 = np.array([[7,8,9],[3,4,5]])
np.stack((m1,m2),axis=-1)

array([[[1, 7],
        [2, 8],
        [3, 9]],

       [[3, 3],
        [4, 4],
        [6, 5]]])