In [7]:
import numpy as np
from google.colab import files
import pandas as pd

In [8]:
uplaoded_file =files.upload()

Saving data.csv to data (1).csv


In [10]:
data = pd.read_csv('data.csv')
print(data)

   Math  Science  English  History  Art
0    12       18       25       30   45
1    22       28       35       40   55
2    32       38       45       50   65
3    42       48       55       60   75
4    52       58       65       70   85


In [14]:
numeric_data = data.select_dtypes(include='number',exclude='string')
print(numeric_data)

   Math  Science  English  History  Art
0    12       18       25       30   45
1    22       28       35       40   55
2    32       38       45       50   65
3    42       48       55       60   75
4    52       58       65       70   85


In [17]:
matrix = numeric_data.to_numpy()
print(matrix)

[[12 18 25 30 45]
 [22 28 35 40 55]
 [32 38 45 50 65]
 [42 48 55 60 75]
 [52 58 65 70 85]]


In [23]:
for x in matrix[0:5]:
  print("student {x} stats: ")
  row = x
  print("Total Marks: ", np.sum(row))
  print("Mean: ",np.mean(row))
  print("Median: ",np.median(row))
  print("Standard Deviation: ",np.std(row))
  print("Variance: ",np.var(row))
  print("Min: ",np.min(row))
  print("Max: ",np.max(row))


student {x} stats: 
Total Marks:  130
Mean:  26.0
Median:  25.0
Standard Deviation:  11.29601699715435
Variance:  127.6
Min:  12
Max:  45
student {x} stats: 
Total Marks:  180
Mean:  36.0
Median:  35.0
Standard Deviation:  11.29601699715435
Variance:  127.6
Min:  22
Max:  55
student {x} stats: 
Total Marks:  230
Mean:  46.0
Median:  45.0
Standard Deviation:  11.29601699715435
Variance:  127.6
Min:  32
Max:  65
student {x} stats: 
Total Marks:  280
Mean:  56.0
Median:  55.0
Standard Deviation:  11.29601699715435
Variance:  127.6
Min:  42
Max:  75
student {x} stats: 
Total Marks:  330
Mean:  66.0
Median:  65.0
Standard Deviation:  11.29601699715435
Variance:  127.6
Min:  52
Max:  85


In [26]:
sum=np.sum(matrix, axis=0)
means=np.mean(matrix, axis=0)
median =np.median(matrix, axis=0)
std=np.std(matrix, axis=0)
var=np.var(matrix, axis=0)
min=np.min(matrix, axis=0)
max=np.max(matrix, axis=0)



for i in range(len(matrix)):
  print(sum,means,median,std,var,min,max)
  print("-"*30)

[160 190 225 250 325] [32. 38. 45. 50. 65.] [32. 38. 45. 50. 65.] [14.14213562 14.14213562 14.14213562 14.14213562 14.14213562] [200. 200. 200. 200. 200.] [12 18 25 30 45] [52 58 65 70 85]
------------------------------
[160 190 225 250 325] [32. 38. 45. 50. 65.] [32. 38. 45. 50. 65.] [14.14213562 14.14213562 14.14213562 14.14213562 14.14213562] [200. 200. 200. 200. 200.] [12 18 25 30 45] [52 58 65 70 85]
------------------------------
[160 190 225 250 325] [32. 38. 45. 50. 65.] [32. 38. 45. 50. 65.] [14.14213562 14.14213562 14.14213562 14.14213562 14.14213562] [200. 200. 200. 200. 200.] [12 18 25 30 45] [52 58 65 70 85]
------------------------------
[160 190 225 250 325] [32. 38. 45. 50. 65.] [32. 38. 45. 50. 65.] [14.14213562 14.14213562 14.14213562 14.14213562 14.14213562] [200. 200. 200. 200. 200.] [12 18 25 30 45] [52 58 65 70 85]
------------------------------
[160 190 225 250 325] [32. 38. 45. 50. 65.] [32. 38. 45. 50. 65.] [14.14213562 14.14213562 14.14213562 14.14213562 14.14